module.exports = {
   purge: ['./components/**/*.js', './pages/**/*.js'],
   theme: {
      extends: {
         colors: {
            ink: {
               high: '#000000',
               medium: '#3F3F3F',
               low: '#D0D0D0',
               background: '#fff',
               foreground: '#000',
               'accent-1': '#FAFAFA',
               'accent-2': '#EAEAEA',
               'accent-3': '#999',
               'accent-4': '#888',
               'accent-5': '#666',
               'accent-6': '#444',
               'accent-7': '#333',
               'accent-8': '#111',
            },
            warning: {
               light: '#F7B955',
               default: '#F5A623',
               dark: '#F49B0B',
            },
            success: {
               light: '#3291FF',
               default: '#0070F3',
               dark: '#0366D6',
            },
            error: {
               light: '#FF1A1A',
               default: '#E00',
               dark: '#C00',
            },
            highlight: {
               magenta: '#FF0080',
               purple: '#F81CE5',
               violet: '#7928CA',
               cyan: '#79FFE1',
            },
            hover: '#F6F6F6',
            dim: '#EAEAEA',
            accent: '#0070F3',
         },
      },
      textColor: (theme) => ({
         ...theme('colors'),
         ink: {
            high: '#000000',
            medium: '#3F3F3F',
            low: '#D0D0D0',
         },
         warning: {
            light: '#F7B955',
            default: '#F5A623',
            dark: '#F49B0B',
         },
         success: {
            light: '#3291FF',
            default: '#0070F3',
            dark: '#0366D6',
         },
         error: {
            light: '#FF1A1A',
            default: '#E00',
            dark: '#C00',
         },
         highlight: {
            magenta: '#FF0080',
            purple: '#F81CE5',
            violet: '#7928CA',
            cyan: '#79FFE1',
         },
         hover: '#F6F6F6',
         dim: '#EAEAEA',
         'accent-1': '#FAFAFA',
         'accent-2': '#EAEAEA',
         'accent-3': '#999',
         'accent-4': '#888',
         'accent-5': '#666',
         'accent-6': '#444',
         'accent-7': '#333',
         'accent-8': '#111',
         accent: '#0070F3',
      }),
      backgroundColor: (theme) => ({
         ...theme('colors'),
         high: '#000000',
         medium: '#3F3F3F',
         low: '#D0D0D0',
         hover: '#F6F6F6',
         dim: '#EAEAEA',
         'accent-1': '#FAFAFA',
         'accent-2': '#EAEAEA',
         'accent-3': '#999',
         'accent-4': '#888',
         'accent-5': '#666',
         'accent-6': '#444',
         'accent-7': '#333',
         'accent-8': '#111',
         accent: '#0070F3',
         warning: {
            light: '#F7B955',
            default: '#F5A623',
            dark: '#F49B0B',
         },
         success: {
            light: '#3291FF',
            default: '#0070F3',
            dark: '#0366D6',
         },
         error: {
            light: '#FF1A1A',
            default: '#E00',
            dark: '#C00',
         },
         highlight: {
            magenta: '#FF0080',
            purple: '#F81CE5',
            violet: '#7928CA',
            cyan: '#79FFE1',
         },
      }),
      stroke: (theme) => ({
         dark: '#000000',
         light: '#FFFFFF',
         accent: '#0070F3',
      }),
      borderColor: (theme) => ({
         ...theme('colors'),
         default: theme('colors.gray.300', 'currentColor'),
         warning: {
            light: '#F7B955',
            default: '#F5A623',
            dark: '#F49B0B',
         },
         success: {
            light: '#3291FF',
            default: '#0070F3',
            dark: '#0366D6',
         },
         error: {
            light: '#FF1A1A',
            default: '#E00',
            dark: '#C00',
         },
         highlight: {
            magenta: '#FF0080',
            purple: '#F81CE5',
            violet: '#7928CA',
            cyan: '#79FFE1',
         },
      }),
   },
   variants: {
      backgroundColor: ['responsive', 'hover'],
      borderColor: ['responsive', 'focus'],
      screen: [''],
   },
   plugins: [],
};
